### ISSUE TITLE
getLoginStatus not working?

### ISSUE THREAD

**Issue by marko1943** [zyra/ngx-facebook#101] opened 2017-09-23 06:15 UTC

**Comment by ihadeed** [comment] 2017-12-11 19:56
Duplicate of #102

**Closed by ihadeed** 2017-12-11 19:56 UTC

**Comment by FedC** [comment] 2018-05-01 22:56
I had to view the source of `src/providers/facebook.ts` to see that it is used this way:
```
fb.getLoginStatus().then(response => {
        console.log(response);
});
```
